name: Sanity Checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - uses: pre-commit/action@v3.0.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  tagging:
    name: "Tagging (dry-run)"
    needs: pre-commit
    runs-on: ubuntu-latest
    outputs:
      net_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
      - run: echo "Calculated Next Tag is ${{ steps.tag_version.outputs.net_tag }}"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: arduino/setup-task@v1
      - name: Lint and tests
        run: |
          task test
