name: "Tag and build"
on:
  push:
    branches: ["main"]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - uses: pre-commit/action@v3.0.1
  tagging:
    name: "Tagging"
    needs: pre-commit
    runs-on: ubuntu-latest
    outputs:
      next_tag: ${{ steps.tag_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update version in pyproject.toml
        run: |
          python scripts/bump_version.py ${{ steps.tag_version.outputs.new_version }}
      - name: Commit and push version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pyproject.toml
          git commit -m "Bump version to ${{ steps.tag_version.outputs.new_version }}"
          git push
      - run: |
          echo Calculated Next Tag is ${{ steps.tag_version.outputs.new_tag }}

  post_slack:
    runs-on: ubuntu-latest
    needs: tagging
    steps:
      - name: Post to a Slack channel
        if: ${{ success() }}
        id: slack_success
        uses: slackapi/slack-github-action@v1.15.0
        with:
          channel-id: 'sdcadmin-operator'
          slack-message: ':cool-doge: `${{github.repository}}` new version: ${{needs.tagging.outputs.next_tag}}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
